### PR TITLE
Upgrades dependencies to golang 1.17

### PR DESCRIPTION
**Pull request by phantomjinx**
* golang is responsible for providing the http server that serves the js frontend

### CODE REVIEW

**Comment by EricWittmann** [comment]
It looks like the build failed. Can you have a look?

**Comment by phantomjinx** [comment]
> It looks like the build failed. Can you have a look?

Build is good. The **Verify Build** action was failing since it was trying to build the main branch rather than checking out the PR commits. Unfortunately, **main** is/was broken since the golang:1.11 image has been removed from dockerhub (hence the upgrade to 1.17) so that was causing the PR action to fail.

So I have split the action into 2 with the original still being triggered by pushes (renamed it). The new **Verify PR Build** action checks out the PR commits and tries to build them. Only problem I came across was that the git-commit-id maven plugin does not like shallow PR commits so throws an error. I have worked around this by setting the skip property on the plugin in the pom.

The settings for pull-requests will have to be updated as its looking for the **Verify Build** action result rather than **Verfiy PR Build**.

**Comment by phantomjinx** [comment]
@EricWittmann 
Did you want to re-review in light of my changes and comments above^ ?

**Comment by EricWittmann** [comment]
Sorry @phantomjinx I dropped the ball on this one.  Don't hesitate to ping me on gchat if I go silent.  :)

**Pull request merged**
