### PR TITLE
fix manifest properties in pwa deploy

### PR DESCRIPTION
**Pull request by blake-mealey**
This fixes the issue described in: https://github.com/Apicurio/apicurito/pull/119#issuecomment-717619035

We modify the `manifest.json` file's `scope` and `start_url` properties before copying the `dist` directory to the site.

As usual I spoke too soon and should have just read your deploy code - I see you're already doing something similar to fix the base href in the `index.html` file so this was an easy addition.

I haven't been able to test this since it only runs on master though.

### CODE REVIEW

**Comment by EricWittmann** [comment]
Didn't see this before I made my change.  But I like this better, so will merge this and remove mine.  Thanks!

**Comment by EricWittmann** [comment]
Looks like it works.  Nice!

**Comment by blake-mealey** [comment]
Is it installable for you now? Still isn't for me :/

BTW, mind marking this PR as hacktoberfest-accepted? :P

**Comment by EricWittmann** [comment]
It worked with my changes to the workflow, and then yours broke it and I didn't double-check.  Fixing now.

**Pull request merged**
